"""empty message

Revision ID: 16dffdf8c610
Revises: a50a84bc3e3a
Create Date: 2020-03-22 03:11:26.012789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16dffdf8c610'
down_revision = 'a50a84bc3e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.String(length=5), nullable=False))
    op.add_column('users', sa.Column('dob', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dob')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
