"""empty message

Revision ID: 282ed479a296
Revises: b1c8ce44ff39
Create Date: 2020-03-22 03:02:06.429610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282ed479a296'
down_revision = 'b1c8ce44ff39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('diseases', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'diseases')
    # ### end Alembic commands ###
