"""empty message

Revision ID: 39d9e8dc7306
Revises: 282ed479a296
Create Date: 2020-03-22 03:05:06.765969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39d9e8dc7306'
down_revision = '282ed479a296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'diseases')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('diseases', mysql.VARCHAR(length=15), nullable=False))
    # ### end Alembic commands ###
