"""empty message

Revision ID: a50a84bc3e3a
Revises: 39d9e8dc7306
Create Date: 2020-03-22 03:05:28.380765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50a84bc3e3a'
down_revision = '39d9e8dc7306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('diseases', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'diseases')
    # ### end Alembic commands ###
