"""empty message

Revision ID: a8cb6368ec7c
Revises: a9b0ea2e8dc2
Create Date: 2020-04-04 14:56:46.123850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8cb6368ec7c'
down_revision = 'a9b0ea2e8dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appoinments', sa.Column('end_time', sa.String(length=20), nullable=False))
    op.add_column('appoinments', sa.Column('visit_date', sa.String(length=20), nullable=False))
    op.add_column('appoinments', sa.Column('visit_time', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appoinments', 'visit_time')
    op.drop_column('appoinments', 'visit_date')
    op.drop_column('appoinments', 'end_time')
    # ### end Alembic commands ###
