"""empty message

Revision ID: a9b0ea2e8dc2
Revises: 4f81b71fa28a
Create Date: 2020-04-04 13:14:11.704967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b0ea2e8dc2'
down_revision = '4f81b71fa28a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appoinments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_username', sa.String(length=20), nullable=False),
    sa.Column('doctor_username', sa.String(length=20), nullable=False),
    sa.Column('patient_age', sa.String(length=5), nullable=False),
    sa.Column('appointment_time', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('reason_description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appoinments')
    # ### end Alembic commands ###
