"""empty message

Revision ID: cc6419cac1e9
Revises: 171261dcce9b
Create Date: 2020-03-22 02:56:06.189537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6419cac1e9'
down_revision = '171261dcce9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('diseases', sa.String(length=10), nullable=False))
    op.add_column('users', sa.Column('height', sa.String(length=5), nullable=False))
    op.add_column('users', sa.Column('weight', sa.String(length=5), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weight')
    op.drop_column('users', 'height')
    op.drop_column('users', 'diseases')
    # ### end Alembic commands ###
